### ISSUE TITLE
move sidebar file to the platformatic/platformatic repo

### ISSUE THREAD

**Issue by mcollina** [platformatic/docs#107]

**Comment by iamfortune** [comment]
I will be working on this from tomorrow 😄

**Comment by iamfortune** [comment]
Working on the {{project with Matteo}} instead and will push this for when I am done

**Comment by iamfortune** [comment]
Created a [PR](https://github.com/platformatic/docs/pull/119) for this.

**Comment by iamfortune** [comment]
This is done and I am closing this issue.
