### ISSUE TITLE
`newApiProjectInstructions` component is not shown in current docs version `1.52.2`

### ISSUE THREAD

**Issue by 404answernotfound** [platformatic/docs#147]
`newApiProjectInstructions` component is not shown in current docs version `1.52.2`

![Screenshot 2024-08-02 at 12 12 42](https://github.com/user-attachments/assets/00096f67-b9b7-42c2-831f-31e3459bfd81)

![Screenshot 2024-08-02 at 12 12 56](https://github.com/user-attachments/assets/cbea4805-abf4-482d-bb75-3d1b28f3ce35)

I'm having issues running the `docs` locally, so I'm sharing this as an issue. Thanks :)

**Comment by mcollina** [comment]
@iamfortune can you take a look?

**Comment by iamfortune** [comment]
Hi @404answernotfound, Thanks for pointing this out; I've created a PR to fix it now. Do let us know if you have any more issues or suggestions.
