### ISSUE TITLE
Indexing on Google

### ISSUE THREAD

**Issue by mcollina** [platformatic/docs#52]
There is a problem that Google reported related to indexing of certain pages: https://search.google.com/u/1/search-console/index/drilldown?resource_id=sc-domain%3Aplatformatic.dev&item_key=CAMYECAC&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=en-GB&sharing_key=rWil4khuSA3cNAWUALb00A.

I think we should not let Google index anything but the latest release. Wdyt?

**Comment by HassanBahati** [comment]
> There is a problem that Google reported related to indexing of certain pages: https://search.google.com/u/1/search-console/index/drilldown?resource_id=sc-domain%3Aplatformatic.dev&item_key=CAMYECAC&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=en-GB&sharing_key=rWil4khuSA3cNAWUALb00A.

unfortunately cannot view contents of the attached link...perharps could share a screenshot?
![image](https://user-images.githubusercontent.com/65954740/235979752-9e296c25-3d21-474b-be63-ec915fafdde1.png)
